### ISSUE TITLE
Detect targets in included files

### ISSUE THREAD

**Issue by FabianInostroza** [AtomBuild/atom-build-make#13]
The default method for target extractions doesn't detect targets that are defined on included files in the Makefile.

**Comment by noseglid** [comment]
Have you enabled the `useMake` configuration setting?

**Comment by FabianInostroza** [comment]
Yes, using make to get the targets does work, but also lists repeated targets (the other issue that I filed).

**Comment by FabianInostroza** [comment]
Accidentally closed the issue.

**Comment by noseglid** [comment]
I think this issue should stay closed. Using regexes to parse includes and other obscure make features would just not be feasible and I wouldn't want to maintain it.

Let's track the multiple targets issue in #14

**Comment by mshick** [comment]
@noseglid I have a similar issue. I'd like to try useMake, I'm sure it will do what I need, but I haven't been able to figure out how to get the proper config setting. I've tried, in my `config.cson` file every variation I can think of. I've tried an `atom-build.yaml` file with `useMake: true`. No luck!

Do you mind giving a hint on where / how to set this?

**Comment by noseglid** [comment]
@mshick `atom-build-make` is actually a provider for `atom-build`. It will create build configurations. What you need to do is install `build-make` package alongside `build` and it will automatically populate the target list with build targets.

`Use Make` is a configuration setting to `build-make` (set it inside Atom).

**Comment by mshick** [comment]
@noseglid Oh, yeah, I have all that set up. I'm just unable to set the `useMake` var anywhere. I tried every variation of "build-make" and "atom-build" I could come up with in my `config.cson`, but nothing was working...

Having just restarted though, I see the new targets, so that was apparently the trick.

Thanks!
