### ISSUE TITLE
No targets found

### ISSUE THREAD

**Issue by CodingAnarchy** [AtomBuild/atom-build-make#16]
I have a project with two make files (both named Makefile): one in the "src" directory and the other in the "tst" directory.  I'd expect that both of these would be found by the system to be run, but I'm not finding any targets.  I've tried refreshing targets, but no dice.

I've tried running this with the developer tools open, but nothing gets printed to the console or anything that I can tell, so I'm at a loss for any additional info I could provide.  Let me know if there's something I need to do to provide that.

**Comment by noseglid** [comment]
The Makefile must be in the project root. There is no support for having them in subdirectories at the moment, altough [it is being discussed](https://github.com/noseglid/atom-build/issues/317).
