### ISSUE TITLE
Error Matching

### ISSUE THREAD

**Issue by jamesrobb** [AtomBuild/atom-build-make#17]
How would one add error matching to this package such that atom-build would recognize errors in cpp and c files being compiled with gcc/g++ where I could click on the error to jump to the line in question?

**Comment by noseglid** [comment]
There is no errorMatching in this package yet. I'd accept a PR for it though. You can see other packages such as [build-cargo](https://github.com/AtomBuild/atom-build-cargo/blob/master/lib/cargo.js#L55-L61) on how it can be done.
