### ISSUE TITLE
Can't jump to error

### ISSUE THREAD

**Issue by niekez** [AtomBuild/atom-build-make#19]
When an error occurs, it's not possible to jump to the line the error is in. 

![image](https://cloud.githubusercontent.com/assets/6378007/13875439/2d0e5c40-ecfe-11e5-97f1-640c97c4515d.png)

**Comment by noseglid** [comment]
This functionality was _just_ released 30 minutes ago. Which version do you have?

**Comment by niekez** [comment]
I just updated to 0.8.0, the filename and line number are not clickable even after restart.

Running on Linux
building with arm-none-eabi-gcc

Edit: Just noticed it's jumping to the error now, so I guess it's working. Expected the error to be clickable as well.

**Comment by noseglid** [comment]
Does `cmd-alt-g` / `ctrl-alt-g` / `f4` work?

The clickable functionality is not working right now. It's an issue in `build` not this package.

**Comment by niekez** [comment]
f4 is working

**Comment by noseglid** [comment]
Then it matches correctly. Closing this.
