### ISSUE TITLE
build-make ignores environment variables

### ISSUE THREAD

**Issue by Razzile** [AtomBuild/atom-build-make#32]
I have a makefile project that relies on a few outside environment variables but build-make cannot resolve them.
In the below screenshot $THEOS cannot be resolved by build-make
![image](https://cloud.githubusercontent.com/assets/5256381/23905060/ce959ee0-08c1-11e7-9d68-3ccc81825046.png)

**Comment by noseglid** [comment]
The environment [is inherited](https://github.com/noseglid/atom-build/blob/master/lib/build.js#L134), so any environment set for Atom will be set for the spawned command.

Make sure you start atom, and have the environment set the same way as you've done with that shell of yours. Note that if using Atom from e.g. `/Applications`, the same routines as when starting bash may not run.

**Comment by Razzile** [comment]
Just as a reference for anyone else who sees this thread, adding my variables to /etc/profile worked.
