### ISSUE TITLE
Only extract high-level targets

### ISSUE THREAD

**Issue by Leffmann** [AtomBuild/atom-build-make#36]
Large makefiles may contain many dozens of file targets, but most of the time you're only interested in the high-level targets such as "clean", "install" etc.

Would it be a good idea to add an option to only extract the high-level targets as dictated by ".PHONY", and leave out all the clutter of small files?  And similarly, not adding a duplicate "default" target if one has already been extracted from the makefile.

**Comment by no1xsyzy** [comment]
I would need dozens of targets, so I don't think it should be configured globally. Maybe a new pseudo-target for hiding it? like `.HIDEFROMLIST`?
