### ISSUE TITLE
Makefile with other standard naming are not supported

### ISSUE THREAD

**Issue by dzamlo** [AtomBuild/atom-build-make#4]
Different make implementation also recognize some other name for the Makefile.
For example gnu make recognize "makefile" (lower case m) and "GNUmakefile".
I think some BSD make also recognize "MAKEFILE" in addition to "Makefile" and "makefile" but I'm unable to test that.

This package should also work with them.

**Comment by noseglid** [comment]
Thanks for bringing this to my attention. Sorry for taking so long to respond.

The GNU Make [documentation on Makefile names](https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html) says it supports `GNUmakefile`, `Makefile` and `makefile`.

I've made a PR #11 which makes this plugin do the same!
